### ISSUE TITLE
Issue with grep

### ISSUE THREAD

**Issue by xapple** [minos-org/minos-static#3]
I was really happy when I saw this project and think it can have lots of uses. I always thought that the packagers are useless. Wherever it's `apt-get` or `yum` they never thought a `--user` option would be useful and you can only run those programs if you own the machine and are `sudo` on it. Trying to compile software always ends in tears as you chase one dependency after an other. 

As I see it we have gone through over a decade of developer and system administrator centric software distribution and it might only start changing to a user-centric model. 

Developers are often against static linking, but that's what every _user_ wants !

I was unable to compile `tmux` on the server I'm using (it has `SUSE Linux Enterprise Server 11 SP3`) so I tried this command, but it didn't work:

```
xapple@sisu ~ $ sh <(wget -qO- s.minos.io/s) -s -v tmux
Usage: grep [OPTION]... PATTERN [FILE]...
Try `grep --help' for more information.
```

This command did work perfectly however:

```
xapple@sisu ~ $ sh <(wget -qO- http://s.minos.io/s) -x tmux-2.1
```

**Comment by javier-lopez** [comment]
Hello Lucas,

I agree with your comments, and although I don't think static binaries are the perfect panacea they have indeed their use cases.

Thank you for the catch =), I'll provide a fix ASAP, although due to a busy schedule it could take some days. In the meantime you can use:

`sh <(wget -qO- s.minos.io/s) -v -s tmux #-s stands for search [pattern]`

To search for packages.

Best regards,
JL

**Comment by javier-lopez** [comment]
Hello Lucas,

I've just committed https://github.com/minos-org/minos-static/commit/9ba617283a46d439398042e8597934d24e514b4a which attempts to fix the problem. Let me know if you find any issue.

Cheers,
JL

**Comment by xapple** [comment]
It seems to be working fine !
