### ISSUE TITLE
Request for latest tmux

### ISSUE THREAD

**Issue by xapple** [minos-org/minos-static#4]
Hi !

A new version of tmux 2.2 is out since April 10. Do you think you could add it to the repository ? Thanks !

**Comment by javier-lopez** [comment]
Hello,

I've just added it in commit https://github.com/minos-org/bifrost-build/commit/c356271e0453dfa4fa41e163ad83f59b4352a870 since I don't follow any particular upstream I recommend to open issues to request new packages or send your push request if you're in a hurry.

Let me know if you find any issues with the build.

**Comment by xapple** [comment]
Hey that looks great ! Thanks a lot !
So what steps remain for the following commands to work ?

```
$ sh <(wget -qO- http://s.minos.io/s) -x tmux-2.2
```

or

```
 $ static-get tmux-2.2
```

Anything I can help you with ?

**Comment by javier-lopez** [comment]
You have to clean the index cache

```
$ sh <(wget -qO- http://s.minos.io/s) -c
```

And then retry

```
$ sh <(wget -qO- http://s.minos.io/s) -x tmux-2.2
```

Bests

**Comment by xapple** [comment]
Ahh I see ! Perfect ! Thanks a lot ! I was able to download it !
Just a strange thing that didn't happen with the other version:

```
xapple@login4 ~ $ export LANGUAGE="en_US.UTF-8"
xapple@login4 ~ $ export LANG="en_US.UTF-8"
xapple@login4 ~ $ export LC_ALL="en_US.UTF-8"
xapple@login4 ~ $ export LC_CTYPE="en_US.UTF-8"
xapple@login4 ~ $ export CTYPE="en_US.UTF-8"
xapple@login4 ~ $ tmux -V
tmux: need UTF-8 locale (LC_CTYPE) but have ASCII
tmux 2.2
```

But I should probably open a ticket at the developer's repository for that I suppose.

**Comment by javier-lopez** [comment]
Indeed, that's kind of weird, I actually had to add a patch https://github.com/minos-org/bifrost-build/commit/75fbfb7627a3ce3f35e88f251fa2f3084d6920e1 so it could continue instead of halting, not sure if has anything to do with being built statically, [upstream reply](https://groups.google.com/forum/#!topic/tmux-users/BnMK0ijLSIE) is than local locate settings are incorrect.

**Comment by xapple** [comment]
Yeah it's strange. I was finally able to finally compile and build tmux 2.2 on my the box where I want to use it, against all expectations. And that version does not complain about the locale when I use it. So it seems like it's something from your side.

**Comment by javier-lopez** [comment]
Awesome,

Thank you for testing, then it will definitely is related to the static environment. I could look closer but to be honest it works good enough on my side so it may take some time. Anyway, if someone else is interested in debugging the issue, the recipe is locate at:

https://github.com/minos-org/bifrost-build/tree/master/all/tmux-2.2-1
