### ISSUE TITLE
download integrity?

### ISSUE THREAD

**Issue by ChaosData** [minos-org/minos-static#9]
Hi,

A quick skim through the static-get source seems to indicate that downloads are hardcoded to use plaintext HTTP, and that one only specifies the hostname+ part of the URL as a mirror. As this seems to indicate that there is no transport encryption/integrity in place, is there some other signing scheme used? I can't seem to find any use of gpg or openssl in the script.

**Comment by javier-lopez** [comment]
Hello @ChaosData, indeed it forces to use http but only if the defined mirror fails, which could use https, it's forced on such scenarios because static-get could be executed on systems where the fetcher (wget|curl|fetch) doesn't auto add http:// to the beginning of urls, that's for the encryption part, for integrity, static-get uses md5 | shasum 512, whichever is available on the system.
